@startuml BalloonStateの状態遷移図
title BalloonStateの状態遷移図


[*] --> BalloonStatePreparing
BalloonStatePreparing --> BalloonStateReady : Timeout
BalloonStateReady --> BalloonStatePopping : onStamp
BalloonStatePopping --> [*] : Timeout
BalloonStateReady --> BalloonStateAway : Timeout
BalloonStateAway --> [*]


@enduml

