@startuml BalloonStateの状態遷移図
title BalloonStateの状態遷移図


[*] --> BalloonStatePreparing
BalloonStatePreparing --> BalloonStateReady : Timeout random
BalloonStateReady --> BalloonStatePopping : onStamp
BalloonStatePopping --> BalloonStatePreparing : Timeout constant
BalloonStateReady --> BalloonStateAway : Timeout constant
BalloonStateAway --> BalloonStatePreparing : Timeout constant


@enduml

