@startuml SceneStateの状態遷移図
title SceneStateの状態遷移図


[*] --> SceneStateTitle

SceneStateTitle --> SceneStatePlaying : Any KeyDown

SceneStatePlaying --> SceneStateResult : Timeout

SceneStateResult --> SceneStateTitle : Any KeyDown / Submit High-score

@enduml

