@startuml SceneStateの状態遷移図
title SceneStateの状態遷移図


[*] --> SceneStateTitle

SceneStateTitle --> SceneStatePlaying

SceneStatePlaying --> SceneStateResult

SceneStateResult --> SceneStateTitle

@enduml

